### ISSUE TITLE
Typescript cannot find types due to exports in package.json

### ISSUE THREAD

**Issue by karl977** [cm226/y-textarea#10]
Hi!

First of all thanks for creating this library. Very useful.

The current exports in `package.json` cause types not to by found by Typescript. This is also reported by https://arethetypeswrong.github.io/?p=y-textarea%401.0.0

I edited exports with `patch-package` and solved the issue with the following:
```json
"exports": {
    ".": {
      "import": {
        "types": "./dist/y-textArea.d.ts",
        "default": "./dist/y-textArea.es.js"
      },
      "require": {
        "types": "./dist/y-textArea.d.ts",
        "default": "./dist/y-textArea.umd.js"
      }
    }
  },
```

I think the problem occurs when `moduleResolution: bundler` is set in `tsconfig.json`. This is the default mode for my Next.js 14 project and I cannot change it.

Here's the problem reported by my editor:
![issue](https://github.com/cm226/y-textarea/assets/4600229/25e736c8-c727-4148-baf3-1dd131a51c37)

I found the solution in a discussion about the problem: https://github.com/microsoft/TypeScript/issues/52363

**Comment by cm226** [comment]
Hi, @karl977 

Thanks for your thorough problem description. I understand the issue. It looks like the fix you suggest seems to resolve the issues on https://arethetypeswrong.github.io

I read https://github.com/microsoft/TypeScript/issues/52363 based on the final comment "**The key issue is that a single declaration file cannot describe two modules of different formats, even if the syntax within is the same**." I wonder if the suggested fix is correct? TBH I don't really understand why separate types are needed yet for different targets, but it seems they are (now?). 

Since y-textarea doesn't provide a cjs file I wonder if it is just OK to use the same type file for all the exports. Ill take a closer look at this soon.
