### ISSUE TITLE
Replace selection causes appearance of additional character

### ISSUE THREAD

**Issue by mk45** [cm226/y-textarea#6]
Steps to reproduce:
Write some text with big letters 
<img width="284" alt="Zrzut ekranu 2022-12-15 o 15 12 29" src="https://user-images.githubusercontent.com/1402916/207882870-6cf142a0-fbc5-4289-81a1-bb88e8668855.png">

select some text
<img width="247" alt="Zrzut ekranu 2022-12-15 o 15 13 18" src="https://user-images.githubusercontent.com/1402916/207883068-35748553-b124-4a2a-ae85-d5624392cf77.png">

over-write very very fast selcted word (no paste) 
<img width="222" alt="Zrzut ekranu 2022-12-15 o 15 14 18" src="https://user-images.githubusercontent.com/1402916/207883294-d8ff2a7e-07ca-40dc-99be-67a31c7c8a7a.png">

**Comment by cm226** [comment]
Hey @mk45 Thanks for raising! 
It will probably be the weekend before i get a chance to look at this. 

It looks like from your example there is a reordering of characters the ',' is appearing in the middle of your new text. I'll need to refresh my memory of y-js merging but i think it should prevent this. Perhaps this is coming about because of something In the text diffing on change.

**Comment by cm226** [comment]
I failed to repro this, and no more information was given so closing.
